import assert from "node:assert/strict";
import test from "node:test";
import {URL} from "node:url";

import {
  addSubtitlesToMasterPlaylist,
  buildSubtitleMediaPlaylist,
  getActiveSubtitleLines,
  getNativeTextTrackSelection,
  getSubtitleChoices,
  getSubtitleTrackList,
  getSubtitleUrl,
  getTranslationOffers,
  parseJson3Subtitles,
  pickSubtitleTrack,
  requiresPoToken,
} from "../src/utils/Subtitles.ts";

const text = value => ({toString: () => value});

const captions = {
  caption_tracks: [
    {
      base_url:
        "https://www.youtube.com/api/timedtext?v=abc&lang=en&fmt=srv3&kind=",
      name: text("English"),
      vss_id: ".en",
      language_code: "en",
      is_translatable: true,
    },
    {
      base_url: "https://www.youtube.com/api/timedtext?v=abc&lang=en&kind=asr",
      name: text("English (auto-generated)"),
      vss_id: "a.en",
      language_code: "en",
      kind: "asr",
      is_translatable: true,
    },
    {
      base_url: "/api/timedtext?v=abc&lang=de-DE",
      name: text("German (Germany)"),
      vss_id: ".de-DE",
      language_code: "de-DE",
      is_translatable: true,
    },
  ],
  translation_languages: [
    {language_code: "fr", language_name: text("French")},
    {language_code: "de", language_name: text("German")},
  ],
};

test("maps caption tracks and fixes relative URLs", () => {
  const list = getSubtitleTrackList(captions);
  assert.equal(list.tracks.length, 3);
  assert.equal(list.tracks[1].autoGenerated, true);
  assert.equal(list.tracks[1].name, "English (auto-generated)");
  assert.equal(
    list.tracks[2].baseUrl,
    "https://www.youtube.com/api/timedtext?v=abc&lang=de-DE",
  );
  assert.equal(getSubtitleTrackList({}), undefined);
  assert.equal(getSubtitleTrackList(undefined), undefined);
});

test("requests json3 and replaces an existing format", () => {
  const list = getSubtitleTrackList(captions);
  const url = new URL(getSubtitleUrl(list.tracks[0]));
  assert.deepEqual(url.searchParams.getAll("fmt"), ["json3"]);
  assert.equal(url.searchParams.get("tlang"), null);
});

test("adds the target language for translations", () => {
  const list = getSubtitleTrackList(captions);
  const [french] = getTranslationOffers(list, ["fr"]);
  assert.equal(french.languageCode, "fr");
  assert.equal(french.name, "French");
  assert.equal(french.translation.sourceName, "English");
  assert.equal(new URL(getSubtitleUrl(french)).searchParams.get("tlang"), "fr");
});

test("offers no translation into a language the video already has", () => {
  const list = getSubtitleTrackList(captions);
  assert.deepEqual(
    getTranslationOffers(list, ["de", "en", undefined, "fr", "fr"]).map(
      t => t.languageCode,
    ),
    ["fr"],
  );
  // Unknown targets are skipped when the client listed its languages.
  assert.deepEqual(getTranslationOffers(list, ["xx"]), []);
});

test("picks the track from the user's preference", () => {
  const list = getSubtitleTrackList(captions);
  assert.equal(pickSubtitleTrack(list, {enabled: false}), undefined);
  assert.equal(pickSubtitleTrack(undefined, {enabled: true}), undefined);
  assert.equal(pickSubtitleTrack(list, {enabled: true}).id, ".en");
  // Manual tracks win over speech recognition in the same language.
  assert.equal(
    pickSubtitleTrack(list, {enabled: true, languageCode: "en"}).id,
    ".en",
  );
  // Regional variants match the plain language.
  assert.equal(
    pickSubtitleTrack(list, {enabled: true, languageCode: "de"}).id,
    ".de-DE",
  );
  // Missing languages fall back to a translation.
  const french = pickSubtitleTrack(list, {enabled: true, languageCode: "fr"});
  assert.equal(french.id, ".en>fr");
});

test("uses the auto-generated track when it is the only one", () => {
  const list = getSubtitleTrackList({
    caption_tracks: [captions.caption_tracks[1]],
  });
  assert.equal(
    pickSubtitleTrack(list, {enabled: true, languageCode: "en"}).id,
    "a.en",
  );
  // Without a list of languages, translation is still offered.
  assert.equal(
    pickSubtitleTrack(list, {enabled: true, languageCode: "de"}).id,
    "a.en>de",
  );
});

test("detects URLs that need a PoToken", () => {
  const [track] = getSubtitleTrackList(captions).tracks;
  assert.equal(requiresPoToken(track), false);
  assert.equal(
    requiresPoToken({...track, baseUrl: `${track.baseUrl}&exp=xpe`}),
    true,
  );
});

// Shape of a real auto-generated json3 document (dQw4w9WgXcQ, shortened).
const asrJson3 = {
  events: [
    {tStartMs: 0, dDurationMs: 211879, id: 1, wpWinPosId: 1},
    {tStartMs: 320, dDurationMs: 14260, wWinId: 1, segs: [{utf8: "[Music]"}]},
    {tStartMs: 18790, wWinId: 1, aAppend: 1, segs: [{utf8: "\n"}]},
    {
      tStartMs: 18800,
      dDurationMs: 7160,
      wWinId: 1,
      segs: [
        {utf8: "We're"},
        {utf8: " no", tOffsetMs: 239},
        {utf8: " strangers", tOffsetMs: 559},
      ],
    },
    {
      tStartMs: 21790,
      dDurationMs: 4170,
      wWinId: 1,
      aAppend: 1,
      segs: [{utf8: "\n"}],
    },
    {
      tStartMs: 21800,
      dDurationMs: 7319,
      wWinId: 1,
      segs: [{utf8: "love."}, {utf8: " You", tOffsetMs: 1000}],
    },
  ],
};

test("parses json3 and drops windows and appended line breaks", () => {
  const cues = parseJson3Subtitles(asrJson3);
  assert.deepEqual(
    cues.map(c => [c.startMs, c.endMs]),
    [
      [320, 14580],
      [18800, 25960],
      [21800, 29119],
    ],
  );
  assert.deepEqual(parseJson3Subtitles(undefined), []);
  assert.deepEqual(parseJson3Subtitles({events: "x"}), []);
});

test("reveals auto-generated words at their offset", () => {
  const cues = parseJson3Subtitles(asrJson3);
  assert.deepEqual(getActiveSubtitleLines(cues, 1000), ["[Music]"]);
  assert.deepEqual(getActiveSubtitleLines(cues, 16000), []);
  assert.deepEqual(getActiveSubtitleLines(cues, 18900), ["We're"]);
  assert.deepEqual(getActiveSubtitleLines(cues, 19500), ["We're no strangers"]);
  // Overlapping cues form the rolling two-line window.
  assert.deepEqual(getActiveSubtitleLines(cues, 23000), [
    "We're no strangers",
    "love. You",
  ]);
  assert.deepEqual(getActiveSubtitleLines(cues, 23000, 1), ["love. You"]);
});

test("keeps line breaks inside manual cues", () => {
  const cues = parseJson3Subtitles({
    events: [
      {
        tStartMs: 22640,
        dDurationMs: 4320,
        segs: [{utf8: "You know the rules\nand so do I"}],
      },
    ],
  });
  assert.deepEqual(getActiveSubtitleLines(cues, 23000), [
    "You know the rules",
    "and so do I",
  ]);
  assert.deepEqual(getActiveSubtitleLines(cues, 26960), []);
});

test("lists the video's tracks before translation offers", () => {
  const list = getSubtitleTrackList(captions);
  assert.deepEqual(
    getSubtitleChoices(list, ["fr", "de"]).map(t => t.id),
    [".en", "a.en", ".de-DE", ".en>fr"],
  );
  assert.deepEqual(getSubtitleChoices(undefined, ["fr"]), []);
});

test("builds a single-segment WebVTT playlist", () => {
  const [track] = getSubtitleTrackList(captions).tracks;
  const lines = buildSubtitleMediaPlaylist(track, 212.4).split("\n");
  assert.equal(lines[0], "#EXTM3U");
  assert.ok(lines.includes("#EXT-X-TARGETDURATION:213"));
  assert.ok(lines.includes("#EXTINF:213,"));
  const url = new URL(lines.find(line => line.startsWith("https://")));
  assert.deepEqual(url.searchParams.getAll("fmt"), ["vtt"]);
  assert.equal(lines.at(-2), "#EXT-X-ENDLIST");
});

// Prettier and the `quotes` rule disagree on literals with double quotes.
const Q = "\u0022";

const master = [
  "#EXTM3U",
  "#EXT-X-INDEPENDENT-SEGMENTS",
  `#EXT-X-MEDIA:TYPE=AUDIO,GROUP-ID=${Q}a${Q},URI=${Q}file:///a.m3u8${Q}`,
  `#EXT-X-STREAM-INF:BANDWIDTH=1,CODECS=${Q}avc1.4d401f${Q},AUDIO=${Q}a${Q}`,
  "file:///v1.m3u8",
  `#EXT-X-STREAM-INF:BANDWIDTH=2,AUDIO=${Q}a${Q}`,
  "file:///v2.m3u8",
].join("\n");

test("adds subtitle renditions and attaches them to every variant", () => {
  const result = addSubtitlesToMasterPlaylist(master, [
    {name: `English ${Q}CC${Q}`, languageCode: "en", uri: "file:///s0.m3u8"},
    {name: "Deutsch", languageCode: "de-DE", uri: "file:///s1.m3u8"},
  ]).split("\n");
  const media = result.filter(l => l.includes("TYPE=SUBTITLES"));
  assert.equal(media.length, 2);
  assert.equal(
    media[0],
    `#EXT-X-MEDIA:TYPE=SUBTITLES,GROUP-ID=${Q}subs${Q},LANGUAGE=${Q}en${Q},` +
      `NAME=${Q}English 'CC'${Q},DEFAULT=NO,AUTOSELECT=YES,` +
      `URI=${Q}file:///s0.m3u8${Q}`,
  );
  // Renditions precede the first variant that references them.
  assert.ok(
    result.indexOf(media[1]) <
      result.findIndex(l => l.startsWith("#EXT-X-STREAM-INF")),
  );
  for (const line of result.filter(l => l.startsWith("#EXT-X-STREAM-INF"))) {
    assert.ok(line.endsWith(`,SUBTITLES=${Q}subs${Q}`), line);
  }
  // Variant URIs stay in place.
  assert.equal(result.at(-1), "file:///v2.m3u8");
});

test("leaves the master alone without renditions", () => {
  assert.equal(addSubtitlesToMasterPlaylist(master, []), master);
});

test("selects the native text track from the preference", () => {
  const list = getSubtitleTrackList(captions);
  const label = track => `label:${track.id}`;
  const auto = list.tracks[1];
  // Never decided: the system chooses.
  assert.equal(
    getNativeTextTrackSelection(auto, {}, "title", label),
    undefined,
  );
  assert.deepEqual(
    getNativeTextTrackSelection(auto, {enabled: false}, "title", label),
    {type: "disabled"},
  );
  assert.deepEqual(
    getNativeTextTrackSelection(undefined, {enabled: true}, "title", label),
    {type: "disabled"},
  );
  // The generated manifest is matched by name, as manual and speech
  // recognition tracks share a language.
  assert.deepEqual(
    getNativeTextTrackSelection(auto, {enabled: true}, "title", label),
    {type: "title", value: "label:a.en"},
  );
  assert.deepEqual(
    getNativeTextTrackSelection(auto, {enabled: true}, "language", label),
    {type: "language", value: "en"},
  );
});
