branches:
  - main
  - next
  - name: tests
    prerelease: true
  - name: beta
    prerelease: true
  - name: alpha
    prerelease: true

plugins:
  - - "@semantic-release/commit-analyzer"
    - releaseRules:
        - type: build
          release: patch
        - type: ci
          release: patch
        - type: chore
          release: patch
        - type: docs
          release: patch
        - type: refactor
          release: patch
        - type: style
          release: patch
        - type: test
          release: patch
        - type: feat
          release: minor
        - type: fix
          release: patch
        - type: perf
          release: patch
        - type: breaking
          release: major
  - - '@semantic-release/release-notes-generator'
    - preset: "conventionalcommits"
      presetConfig:
        types:
          - type: breaking
            section: ":exclamation: BREAKING"
            hidden: false
          - type: feat
            section: ":sparkles: Features"
            hidden: false
          - type: fix
            section: ":bug: Fixes"
            hidden: false
          - type: docs
            section: ":memo: Documentation"
            hidden: false
          - type: ci
            section: ":repeat: CI"
            hidden: false
          - type: style
            section: ":barber: Style"
            hidden: false
          - type: refactor
            section: ":zap: Refactor"
            hidden: false
          - type: perf
            section: ":fast_forward: Performance"
            hidden: false
          - type: test
            section: ":white_check_mark: Testes"
            hidden: false
          - type: chore
            section: "Minor changes"
            hidden: false
  - '@semantic-release/npm'
  - - '@semantic-release/changelog'
    - changelogFile: "CHANGELOG.md"
  - - "@semantic-release/git"
    - assets: [ "CHANGELOG.md", "package.json" ]
      message: "chore(release): ${nextRelease.version} [skip ci]\n\n${nextRelease.notes}"
  - '@semantic-release/github'

npmPublish: false
