branches:
  - name: main
    prerelease: true # Currently only release beta releases
  - next
  - name: beta
    prerelease: true
  - name: alpha
    prerelease: true

plugins:
  - - "@semantic-release/commit-analyzer"
    - releaseRules:
        - type: build
          release: patch
        - type: ci
          release: patch
        - type: chore
          release: patch
        - type: docs
          release: patch
        - type: refactor
          release: patch
        - type: style
          release: patch
        - type: test
          release: patch
        - type: feat
          release: minor
        - type: fix
          release: patch
        - type: perf
          release: patch
        - type: breaking
          release: major
  - '@semantic-release/release-notes-generator'
  - '@semantic-release/npm'
  - '@semantic-release/github'

npmPublish: false
tarballDir: false

preset: 'angular'
