branches:
  - name: main
    prerelease: true # Currently only release beta releases
  - next
  - tests
  - name: beta
    prerelease: true
  - name: alpha
    prerelease: true

plugins:
  - "@semantic-release/commit-analyzer"
  - - '@semantic-release/release-notes-generator'
    - writerOpts:
        commitGroupsSort: [
          "breaking",
          "feat",
          "fix",
          "revert",
          "refactor",
          "perf",
          "docs",
          "style",
          "build",
          "chore",
          "upgrade",
          "ci"
        ]
  - '@semantic-release/npm'
  - '@semantic-release/github'

npmPublish: false

preset: 'angular'
