// plugins/android/withTVDisplayScaling.js
const {
  AndroidConfig,
  withDangerousMod,
  withMainActivity,
  withMainApplication,
} = require("@expo/config-plugins");
const {
  mergeContents,
} = require("@expo/config-plugins/build/utils/generateCode");
const fs = require("node:fs");
const path = require("node:path");

/**
 * tvOS lays out every Apple TV on a 1920 x 1080 point surface, while Android TV
 * reports its panel at xhdpi, i.e. 960 x 540 dp on a 1080p screen. The shared
 * TV design is sized for the tvOS surface, so on Android TV everything renders
 * at twice the intended size. This plugin rescales the density on TV devices so
 * that the logical width is always 1920 dp, which keeps both TV platforms on
 * the same coordinate space. Phones and tablets are left untouched at runtime.
 */
const TAG = "reacttube-tv-display-scaling";

function scalingSource(packageName) {
  return `package ${packageName}

import android.content.Context
import android.content.res.Configuration
import android.util.DisplayMetrics
import com.facebook.react.uimanager.DisplayMetricsHolder
import kotlin.math.max
import kotlin.math.min
import kotlin.math.roundToInt

/**
 * Gives TV devices the logical 1920 dp wide surface tvOS uses, so the shared TV
 * design renders at the same size on both platforms. Generated by
 * plugins/android/withTVDisplayScaling.js.
 */
object TVDisplayScaling {
  private const val TARGET_WIDTH_DP = 1920

  private fun isTelevision(context: Context): Boolean {
    val uiModeType = context.resources.configuration.uiMode and Configuration.UI_MODE_TYPE_MASK
    return uiModeType == Configuration.UI_MODE_TYPE_TELEVISION
  }

  fun wrap(base: Context): Context {
    if (!isTelevision(base)) {
      return base
    }

    val configuration = base.resources.configuration
    val metrics = base.resources.displayMetrics
    val widthPx = max(metrics.widthPixels, metrics.heightPixels)
    val heightPx = min(metrics.widthPixels, metrics.heightPixels)
    if (widthPx <= 0) {
      return base
    }

    val densityDpi =
        (widthPx * DisplayMetrics.DENSITY_DEFAULT.toFloat() / TARGET_WIDTH_DP).roundToInt()
    if (densityDpi <= 0 || densityDpi == configuration.densityDpi) {
      return base
    }

    val scaled = Configuration(configuration)
    scaled.densityDpi = densityDpi
    scaled.screenWidthDp = widthPx * DisplayMetrics.DENSITY_DEFAULT / densityDpi
    scaled.screenHeightDp = heightPx * DisplayMetrics.DENSITY_DEFAULT / densityDpi
    scaled.smallestScreenWidthDp = scaled.screenHeightDp
    return base.createConfigurationContext(scaled)
  }

  /**
   * React Native reads the screen density from Display.getRealMetrics(), which
   * ignores the configuration override above and keeps reporting the panel
   * density. Text would then be measured at one density and drawn at the
   * other, so the screen metrics are realigned with the scaled resources each
   * time React Native may have recomputed them.
   */
  fun syncReactNativeMetrics(context: Context) {
    val appContext = context.applicationContext ?: context
    if (!isTelevision(appContext)) {
      return
    }

    val scaled = appContext.resources.displayMetrics
    val current =
        try {
          DisplayMetricsHolder.getScreenDisplayMetrics()
        } catch (_: IllegalStateException) {
          DisplayMetricsHolder.setWindowDisplayMetrics(scaled)
          null
        }
    if (current != null && current.densityDpi == scaled.densityDpi) {
      return
    }

    val screen = DisplayMetrics()
    screen.setTo(current ?: scaled)
    screen.density = scaled.density
    screen.densityDpi = scaled.densityDpi
    screen.scaledDensity = scaled.scaledDensity
    DisplayMetricsHolder.setScreenDisplayMetrics(screen)
  }
}
`;
}

const attachBaseContextOverride = [
  "  override fun attachBaseContext(base: Context) {",
  "    super.attachBaseContext(TVDisplayScaling.wrap(base))",
  "  }",
].join("\n");

// onContentChanged runs right after React Native creates the root view, which
// recomputes the display metrics, and before any JavaScript reads them.
const activityOverrides = [
  attachBaseContextOverride,
  "",
  "  override fun onContentChanged() {",
  "    super.onContentChanged()",
  "    TVDisplayScaling.syncReactNativeMetrics(this)",
  "  }",
  "",
  "  override fun onConfigurationChanged(newConfig: Configuration) {",
  "    super.onConfigurationChanged(newConfig)",
  "    TVDisplayScaling.syncReactNativeMetrics(this)",
  "  }",
].join("\n");

function addKotlinImport(src, importLine) {
  if (src.includes(importLine)) {
    return src;
  }
  return src.replace(/^(package [^\n]+\n)/, `$1\n${importLine}\n`);
}

function addCode(src, tag, newSrc, anchor, offset) {
  return mergeContents({tag, src, newSrc, anchor, offset, comment: "//"})
    .contents;
}

const withTVDisplayScaling = config => {
  config = withDangerousMod(config, [
    "android",
    async config => {
      const packageName = AndroidConfig.Package.getPackage(config);
      if (!packageName) {
        throw new Error(
          "withTVDisplayScaling: android.package must be set in app.json",
        );
      }
      const targetDir = path.join(
        config.modRequest.platformProjectRoot,
        "app/src/main/java",
        ...packageName.split("."),
      );
      fs.mkdirSync(targetDir, {recursive: true});
      fs.writeFileSync(
        path.join(targetDir, "TVDisplayScaling.kt"),
        scalingSource(packageName),
      );
      return config;
    },
  ]);

  // Both contexts need the override: React Native reads its display metrics
  // from the application context, native views inflate from the activity.
  config = withMainApplication(config, config => {
    let src = addKotlinImport(
      config.modResults.contents,
      "import android.content.Context",
    );
    src = addCode(
      src,
      TAG,
      attachBaseContextOverride,
      /^class MainApplication\b.*\{$/m,
      1,
    );
    // Initializing the metrics first makes React Native skip its own
    // initialization, which would read the unscaled panel density.
    src = addCode(
      src,
      `${TAG}-init`,
      "    TVDisplayScaling.syncReactNativeMetrics(this)",
      /^\s*loadReactNative\(this\)$/m,
      0,
    );
    config.modResults.contents = src;
    return config;
  });

  config = withMainActivity(config, config => {
    let src = addKotlinImport(
      config.modResults.contents,
      "import android.content.Context",
    );
    src = addKotlinImport(src, "import android.content.res.Configuration");
    config.modResults.contents = addCode(
      src,
      TAG,
      activityOverrides,
      /^class MainActivity\b.*\{$/m,
      1,
    );
    return config;
  });

  return config;
};

module.exports = withTVDisplayScaling;
