/**
 * YouTube subtitles, rendered by the app itself.
 *
 * The playback sources are mostly HLS manifests (YouTube's own, the generated
 * one, SABR), and AVPlayer ignores side-loaded text tracks on HLS. So the
 * captions are fetched from the timedtext endpoint as `json3` and drawn above
 * the video, which works the same for every source and for the VLC path.
 *
 * Measured on 2026-10-07: the TV metadata client returns no caption tracks,
 * the stream clients (`TV_SIMPLY`, `IOS`, `VISIONOS`, `ANDROID_VR`, `MWEB`)
 * do, and their URLs work without a PoToken. Only `WEB` URLs carry
 * `exp=xpe` and return an empty body without one. Auto-translation (`tlang`)
 * works but is rate limited with HTTP 429 more readily than plain tracks.
 * Later the same day Google blocked the whole endpoint for the IP with 429,
 * PoToken or not; the subtitle playlists in YouTube's HLS manifest point at
 * the same endpoint, so they are no way around it.
 *
 * This module is pure so it can be tested with the Node test runner.
 */

/** The structural part of youtubei.js' `PlayerCaptionsTracklist` used here. */
export interface CaptionTracklistLike {
  caption_tracks?: {
    base_url: string;
    name: {toString(): string};
    vss_id: string;
    language_code: string;
    kind?: string;
    is_translatable: boolean;
  }[];
  translation_languages?: {
    language_code: string;
    language_name: {toString(): string};
  }[];
}

export interface SubtitleTrack {
  /** Stable within one video; translations append the target language. */
  id: string;
  /** The language the cues are shown in. */
  languageCode: string;
  /** API-provided track name, e.g. "English (auto-generated)". */
  name: string;
  /** YouTube's automatic speech recognition track. */
  autoGenerated: boolean;
  translatable: boolean;
  baseUrl: string;
  /** Set when YouTube translates `baseUrl` into `languageCode`. */
  translation?: {
    sourceName: string;
    /** API-provided name of the target language, if known. */
    languageName?: string;
  };
}

export interface TranslationLanguage {
  languageCode: string;
  name: string;
}

export interface SubtitleTrackList {
  tracks: SubtitleTrack[];
  /** Empty when the client did not report them; translation may still work. */
  translationLanguages: TranslationLanguage[];
}

export interface SubtitlePreference {
  enabled?: boolean;
  /** The language last chosen by the user, e.g. "de" or "en-US". */
  languageCode?: string;
}

export interface SubtitleSegment {
  text: string;
  /** Offset from the cue start; auto-generated tracks reveal word by word. */
  offsetMs: number;
}

export interface SubtitleCue {
  startMs: number;
  endMs: number;
  segments: SubtitleSegment[];
}

export function getSubtitleTrackList(
  captions?: CaptionTracklistLike,
): SubtitleTrackList | undefined {
  const tracks = (captions?.caption_tracks ?? [])
    .filter(track => track.base_url)
    .map<SubtitleTrack>(track => ({
      id: track.vss_id || `${track.language_code}:${track.kind ?? ""}`,
      languageCode: track.language_code,
      name: track.name.toString(),
      autoGenerated: track.kind === "asr",
      translatable: track.is_translatable,
      baseUrl: track.base_url.startsWith("/")
        ? `https://www.youtube.com${track.base_url}`
        : track.base_url,
    }));
  if (tracks.length === 0) {
    return undefined;
  }
  return {
    tracks,
    translationLanguages: (captions?.translation_languages ?? []).map(l => ({
      languageCode: l.language_code,
      name: l.language_name.toString(),
    })),
  };
}

/** "de-DE" and "de" count as the same language for subtitle choices. */
export function isSameLanguage(a?: string, b?: string) {
  if (!a || !b) {
    return false;
  }
  return primaryLanguage(a) === primaryLanguage(b);
}

function primaryLanguage(code: string) {
  return code.toLowerCase().split(/[-_]/)[0];
}

export function createTranslatedTrack(
  source: SubtitleTrack,
  languageCode: string,
  translationLanguages: TranslationLanguage[] = [],
): SubtitleTrack {
  const languageName = (
    translationLanguages.find(l => l.languageCode === languageCode) ??
    translationLanguages.find(l => isSameLanguage(l.languageCode, languageCode))
  )?.name;
  return {
    id: `${source.id}>${languageCode}`,
    languageCode,
    name: languageName ?? languageCode,
    autoGenerated: source.autoGenerated,
    translatable: false,
    baseUrl: source.baseUrl,
    translation: {sourceName: source.name, languageName},
  };
}

/**
 * The track YouTube translates from: a manual track beats the speech
 * recognition, and among those the first listed one, which YouTube orders
 * by relevance.
 */
export function getTranslationSource(list: SubtitleTrackList) {
  const translatable = list.tracks.filter(t => t.translatable);
  return translatable.find(t => !t.autoGenerated) ?? translatable[0];
}

/**
 * Translation offers for the given languages that the video does not already
 * have as a track of its own.
 */
export function getTranslationOffers(
  list: SubtitleTrackList,
  languageCodes: (string | undefined)[],
): SubtitleTrack[] {
  const source = getTranslationSource(list);
  if (!source) {
    return [];
  }
  const offers: SubtitleTrack[] = [];
  for (const code of languageCodes) {
    if (
      !code ||
      list.tracks.some(t => isSameLanguage(t.languageCode, code)) ||
      offers.some(t => isSameLanguage(t.languageCode, code))
    ) {
      continue;
    }
    const known =
      list.translationLanguages.length === 0 ||
      list.translationLanguages.some(l => isSameLanguage(l.languageCode, code));
    if (known) {
      const target =
        list.translationLanguages.find(l => l.languageCode === code)
          ?.languageCode ??
        list.translationLanguages.find(l =>
          isSameLanguage(l.languageCode, code),
        )?.languageCode ??
        code;
      offers.push(
        createTranslatedTrack(source, target, list.translationLanguages),
      );
    }
  }
  return offers;
}

/**
 * Chooses the track for a new video from the user's last choice.
 *
 * Order: a manual track in the preferred language, then the auto-generated
 * one, then a translation into it. Without a preferred language the first
 * manual track wins, so turning subtitles on always shows something.
 */
export function pickSubtitleTrack(
  list: SubtitleTrackList | undefined,
  preference: SubtitlePreference,
): SubtitleTrack | undefined {
  if (!list || !preference.enabled) {
    return undefined;
  }
  const language = preference.languageCode;
  if (!language) {
    return list.tracks.find(t => !t.autoGenerated) ?? list.tracks[0];
  }
  const sameLanguage = list.tracks.filter(t =>
    isSameLanguage(t.languageCode, language),
  );
  const exact = sameLanguage.filter(t => t.languageCode === language);
  const match =
    exact.find(t => !t.autoGenerated) ??
    sameLanguage.find(t => !t.autoGenerated) ??
    exact[0] ??
    sameLanguage[0];
  if (match) {
    return match;
  }
  return getTranslationOffers(list, [language])[0];
}

/**
 * The URL of a track's document: `json3` for the app's own renderer, `vtt`
 * for AVPlayer.
 */
export function getSubtitleUrl(
  track: SubtitleTrack,
  format: "json3" | "vtt" = "json3",
) {
  const url = new URL(track.baseUrl);
  // Some clients (`ANDROID_VR`) already put `fmt=srv3` into the URL; the
  // first value would win over an appended one.
  url.searchParams.set("fmt", format);
  if (track.translation) {
    url.searchParams.set("tlang", track.languageCode);
  } else {
    url.searchParams.delete("tlang");
  }
  return url.toString();
}

/** Whether the URL needs a PoToken that the app does not attach. */
export function requiresPoToken(track: SubtitleTrack) {
  return /[?&]exp=xpe(&|$)/.test(track.baseUrl);
}

interface Json3Event {
  tStartMs?: number;
  dDurationMs?: number;
  aAppend?: number;
  segs?: {utf8?: string; tOffsetMs?: number}[];
}

/**
 * Parses YouTube's `json3` timed text.
 *
 * Window definitions (no `segs`) and the line breaks that auto-generated
 * tracks append to the rolling window (`aAppend`) carry no text of their own;
 * overlapping cues already produce the rolling two-line display.
 */
export function parseJson3Subtitles(data: unknown): SubtitleCue[] {
  const events = (data as {events?: Json3Event[]} | undefined)?.events;
  if (!Array.isArray(events)) {
    return [];
  }
  const cues: SubtitleCue[] = [];
  for (const event of events) {
    if (!event.segs || event.aAppend || event.tStartMs === undefined) {
      continue;
    }
    const segments = event.segs
      .filter(seg => seg.utf8)
      .map(seg => ({text: seg.utf8 as string, offsetMs: seg.tOffsetMs ?? 0}));
    if (!segments.some(seg => seg.text.trim())) {
      continue;
    }
    cues.push({
      startMs: event.tStartMs,
      endMs: event.tStartMs + (event.dDurationMs ?? 0),
      segments,
    });
  }
  return cues.sort((a, b) => a.startMs - b.startMs);
}

/**
 * The lines to show at a playback time.
 *
 * Words of a cue appear at their own offset, as on YouTube. Only the last
 * `maxLines` lines are kept so overlapping auto-generated cues cannot pile up.
 */
export function getActiveSubtitleLines(
  cues: SubtitleCue[],
  timeMs: number,
  maxLines = 3,
): string[] {
  const lines: string[] = [];
  for (const cue of cues) {
    if (cue.startMs > timeMs) {
      break;
    }
    if (timeMs >= cue.endMs) {
      continue;
    }
    const text = cue.segments
      .filter(seg => cue.startMs + seg.offsetMs <= timeMs)
      .map(seg => seg.text)
      .join("");
    for (const line of text.split("\n")) {
      const trimmed = line.trim();
      if (trimmed) {
        lines.push(trimmed);
      }
    }
  }
  return lines.slice(-maxLines);
}

/** HLS group id of the subtitle renditions added to a master playlist. */
export const HLS_SUBTITLE_GROUP = "subs";

/**
 * A WebVTT media playlist with the whole track as one segment.
 *
 * This mirrors the subtitle playlists in YouTube's own HLS manifest, which
 * also point one segment at the timedtext endpoint. AVPlayer only fetches it
 * once the rendition is selected, so unused tracks cost no request.
 */
export function buildSubtitleMediaPlaylist(
  track: SubtitleTrack,
  durationSeconds: number,
) {
  const duration = Math.max(1, Math.ceil(durationSeconds));
  return [
    "#EXTM3U",
    "#EXT-X-VERSION:3",
    "#EXT-X-PLAYLIST-TYPE:VOD",
    `#EXT-X-TARGETDURATION:${duration}`,
    `#EXTINF:${duration},`,
    getSubtitleUrl(track, "vtt"),
    "#EXT-X-ENDLIST",
    "",
  ].join("\n");
}

export interface HlsSubtitleRendition {
  name: string;
  languageCode: string;
  uri: string;
}

/** Quotes are not allowed inside a quoted HLS attribute value. */
function hlsAttribute(value: string) {
  return value.replace(/["\r\n]/g, "'");
}

/**
 * Adds subtitle renditions to a master playlist and attaches the group to
 * every variant, which HLS requires for them to be selectable.
 */
export function addSubtitlesToMasterPlaylist(
  master: string,
  renditions: HlsSubtitleRendition[],
): string {
  if (renditions.length === 0) {
    return master;
  }
  const media = renditions.map(
    rendition =>
      "#EXT-X-MEDIA:TYPE=SUBTITLES," +
      `GROUP-ID="${HLS_SUBTITLE_GROUP}",` +
      `LANGUAGE="${hlsAttribute(rendition.languageCode)}",` +
      `NAME="${hlsAttribute(rendition.name)}",` +
      "DEFAULT=NO,AUTOSELECT=YES," +
      `URI="${hlsAttribute(rendition.uri)}"`,
  );
  const lines = master.split("\n");
  const firstVariant = lines.findIndex(line =>
    line.startsWith("#EXT-X-STREAM-INF"),
  );
  if (firstVariant < 0) {
    return master;
  }
  const withGroup = lines.map(line =>
    line.startsWith("#EXT-X-STREAM-INF") && !/[:,]SUBTITLES=/.test(line)
      ? `${line},SUBTITLES="${HLS_SUBTITLE_GROUP}"`
      : line,
  );
  withGroup.splice(firstVariant, 0, ...media);
  return withGroup.join("\n");
}

/**
 * The text track the native player should start with, as a
 * `react-native-video` `selectedTextTrack`.
 *
 * `undefined` leaves the choice to the system (and tvOS' own subtitle
 * settings) as long as the user never decided in the app. A rendition the
 * app wrote itself is matched by its unique name, since the speech
 * recognition and the manual track share a language; YouTube's own manifest
 * names its renditions differently and only has manual tracks, so it is
 * matched by language.
 */
export function getNativeTextTrackSelection(
  track: SubtitleTrack | undefined,
  preference: SubtitlePreference,
  matchBy: "title" | "language",
  label: (track: SubtitleTrack) => string,
):
  | {type: "disabled"}
  | {type: "title" | "language"; value: string}
  | undefined {
  if (preference.enabled === undefined) {
    return undefined;
  }
  if (!preference.enabled || !track) {
    return {type: "disabled"};
  }
  return matchBy === "title"
    ? {type: "title", value: label(track)}
    : {type: "language", value: track.languageCode};
}

/**
 * Every track offered for a video: its own tracks, then translations into
 * the languages the user reads (UI, YouTube content language, last choice).
 */
export function getSubtitleChoices(
  list: SubtitleTrackList | undefined,
  languageCodes: (string | undefined)[],
): SubtitleTrack[] {
  if (!list) {
    return [];
  }
  return [...list.tracks, ...getTranslationOffers(list, languageCodes)];
}
