import type {TranslationKey} from "./en";

export const de = {
  "common.retry": "Erneut versuchen",
  "common.cancel": "Abbrechen",
  "common.continue": "Weiter",
  "common.close": "Schließen",
  "common.back": "Zurück",
  "common.remove": "Entfernen",
  "common.save": "Speichern",
  "common.saved": "Gespeichert",
  "common.copy": "Kopieren",
  "common.enabled": "Aktiviert",
  "common.disabled": "Deaktiviert",
  "common.loading": "Wird geladen",
  "common.more": "Mehr",
  "navigation.home": "Start",
  "navigation.search": "Suche",
  "navigation.subscriptions": "Abos",
  "navigation.library": "Mediathek",
  "navigation.history": "Verlauf",
  "navigation.myYoutube": "Mein YouTube",
  "navigation.music": "Musik",
  "navigation.downloads": "Downloads",
  "navigation.settings": "Einstellungen",
  "navigation.login": "Anmelden",
  "navigation.you": "Du",
  "navigation.account": "Konto",
  "navigation.video": "Video",
  "navigation.channel": "Kanal",
  "navigation.playlists": "Playlists",
  "navigation.playlist": "Playlist",
  "navigation.activeDownloads": "Aktive Downloads",
  "navigation.activeUploads": "Aktive Uploads",
  "navigation.watchLibrary": "Apple Watch",
  "navigation.musicLibrary": "Musikmediathek",
  "navigation.musicSearch": "Musiksuche",
  "navigation.musicPlaylist": "Musikplaylist",
  "navigation.musicChannel": "Musikkanal",
  "navigation.musicPlayer": "Musikplayer",
  "settings.general": "Allgemein",
  "settings.uiLanguage": "App-Sprache",
  "settings.contentLanguage": "Sprache der YouTube-Inhalte",
  "settings.languages": "Sprachen",
  "settings.language.english": "Englisch",
  "settings.language.german": "Deutsch",
  "settings.videoPlayer": "Videoplayer",
  "settings.videoResolution": "Variante der Videoauflösung",
  "settings.historyEnabled": "Verlauf aktiviert",
  "settings.playbackDiagnostics": "Wiedergabediagnose",
  "settings.playerTypes": "Player-Typen",
  "settings.videoTracking": "Videoverlauf",
  "settings.player.native": "Nativ",
  "settings.player.nativeOverlay": "Natives Overlay (experimentell)",
  "settings.player.vlc": "VLC",
  "settings.resolution.localHls": "Lokales HLS — bis 1080p, mehrsprachig",
  "settings.resolution.localHlsAv1":
    "Lokales HLS + AV1 — 4K (nur Apple TV 4K, 3. Generation)",
  "settings.resolution.youtubeHls":
    "YouTube-HLS — bis 1080p, gemischter Ton (Standard)",
  "settings.resolution.progressive": "Progressiv (kann früh abbrechen)",
  "settings.resolution.sabr": "SABR (experimentell — fällt selbsttätig zurück)",
  "settings.diagnostics.run": "Diagnose starten",
  "settings.diagnostics.running": "Läuft…",
  "settings.diagnostics.sessionUnavailable":
    "Die Innertube-Sitzung ist noch nicht bereit.",
  "settings.diagnostics.hint":
    "Prüft JavaScript-Engine, Player, Clients und den SABR-Segmentabruf mit einem Testvideo. Bitte im Release-Build ausführen, da Debug-Builds eine andere Engine verwenden können.",
  "settings.clearAll": "Alle Daten löschen",
  "settings.logout": "Abmelden",
  "settings.channel": "Kanal",
  "settings.channel.title": "Kanäle",
  "settings.channel.primaryAccount": "Hauptkonto",
  "settings.channel.brandChannel": "Brand-Kanal",
  "settings.channel.loading": "Kanäle werden geladen",
  "settings.channel.loadFailed": "Die Kanäle konnten nicht geladen werden.",
  "settings.channel.signedOut": "Melde dich an, um einen Kanal zu wählen.",
  "settings.channel.noChoice":
    "Diese Anmeldung gehört nur zu {name}. Um altersbeschränkte Videos zu sehen und zwischen deinen Kanälen zu wechseln, melde dich ab und mit deinem Google-Hauptkonto neu an.",
  "settings.channel.hint":
    "Die App tritt als der gewählte Kanal auf, wie im Browser. Altersbeschränkte Videos funktionieren weiter, weil das Hauptkonto angemeldet bleibt.",
  "settings.value.true": "Ein",
  "settings.value.false": "Aus",
  "you.account": "Konto",
  "you.signedIn": "Du bist angemeldet",
  "you.signedOut.title": "Nicht angemeldet",
  "you.signedOut.message":
    "Melde dich an, um Abos, Verlauf und Mediathek zu nutzen.",
  "you.content": "Deine Inhalte",
  "you.app": "App",
  "subscriptions.signedOut.title": "Abos brauchen ein Konto",
  "subscriptions.signedOut.message":
    "Melde dich an, um Kanälen zu folgen und neue Videos hier zu sehen.",
  "login.code": "Dein Code lautet {code}",
  "login.waiting.title": "Bereit zur Anmeldung",
  "login.waiting.message":
    "Starte die Anmeldung, um einen Gerätecode anzufordern.",
  "login.start": "Anmeldung starten",
  "login.openPage": "Anmeldeseite öffnen",
  "login.success": "Erfolgreich angemeldet",
  "navigationRail.expand": "Navigation öffnen",
  "navigationRail.collapse": "Navigation schließen",
  "music.loading": "Titel wird geladen",
  "music.play": "Abspielen",
  "music.pause": "Pause",
  "music.library.empty.title": "Deine Musikmediathek ist leer",
  "music.library.empty.message":
    "Gespeicherte Alben, Playlists und Downloads erscheinen hier.",
  "music.playAll": "Alle abspielen",
  "music.startRadio": "Radio starten",
  "music.save": "Speichern",
  "music.unsave": "Aus Mediathek entfernen",
  "music.sendToWatch": "An Watch senden",
  "music.song": "Song",
  "music.video": "Video",
  "music.author": "Interpret",
  "music.queue": "Als Nächstes",
  "music.lyrics": "Songtext",
  "music.related": "Ähnlich",
  "music.downloadStarted": "Download gestartet",
  "music.downloadComplete": "Download abgeschlossen",
  "music.downloadFailed": "Download fehlgeschlagen",
  "music.addToPlaylist": "Zu Playlist hinzufügen",
  "music.playNext": "Als Nächstes abspielen",
  "music.previous": "Vorheriger Titel",
  "music.next": "Nächster Titel",
  "music.repeat": "Wiederholen",
  "music.shuffle": "Zufallswiedergabe",
  "music.autoplay": "Autoplay {state}",
  "music.autoplay.hint":
    "Fügt ähnliche Titel für eine fortlaufende Wiedergabe hinzu.",
  "music.openArtist": "Interpret öffnen",
  "music.error.loading": "Fehler beim Laden des Titels",
  "music.error.reload": "Titel konnte nicht neu geladen werden",
  "music.error.unavailable": "Titel kann nicht abgespielt werden",
  "music.error.noSource": "Es ist keine abspielbare Audioquelle verfügbar.",
  "music.error.playbackFailed": "Wiedergabe fehlgeschlagen",
  "music.error.playbackInterrupted": "Wiedergabe unterbrochen",
  "music.error.retrying": "{message} Ein erneuter Versuch läuft…",
  "state.empty.title": "Noch keine Inhalte",
  "state.empty.message": "Verfügbare Inhalte werden hier angezeigt.",
  "state.error.title": "Etwas ist schiefgelaufen",
  "state.error.message": "Der Inhalt konnte nicht geladen werden.",
  "database.error.title": "Lokale Datenbank konnte nicht vorbereitet werden",
  "database.error.message":
    "Die Download-Datenbank konnte nicht migriert werden. Du kannst es erneut versuchen, die Datenbank reparieren oder zurücksetzen.",
  "database.error.repairing": "Datenbank wird repariert…",
  "database.action.retry": "Erneut versuchen",
  "database.action.repair": "Datenbank reparieren",
  "database.action.reset": "Datenbank zurücksetzen",
  "database.action.details": "Details anzeigen",
  "database.action.hideDetails": "Details verbergen",
  "database.action.copyDetails": "Details kopieren",
  "database.repair.hint":
    "Beim Reparieren wird die Datenbank neu aufgebaut und so viele Informationen wie möglich übernommen. Beim Zurücksetzen werden alle Playlist- und Download-Informationen gelöscht; heruntergeladene Dateien bleiben auf dem Gerät.",
  "database.reset.confirmTitle": "Datenbank zurücksetzen?",
  "database.reset.confirmMessage":
    "Alle lokalen Playlist- und Download-Informationen werden gelöscht. Das kann nicht rückgängig gemacht werden.",
  "database.recovered":
    "Die lokale Datenbank musste beim Start repariert werden.",
  "media.videoCount": "{count} Videos",
  "media.badge.live": "Live",
  "media.badge.mix": "Mix",
  "media.badge.downloaded": "Heruntergeladen",
  "media.badge.4k": "4K",
  "media.badge.8k": "8K",
  "media.progress": "{percent}% angesehen",
  "media.hint.video": "Öffnet das Video",
  "media.hint.playlist": "Öffnet die Playlist",
  "media.hint.channel": "Öffnet den Kanal",
  "media.thumbnailUnavailable": "Vorschaubild nicht verfügbar",
  "media.moreOptions": "Weitere Optionen",
  "feed.refresh": "Aktualisieren",
  "feed.loadingMore": "Weitere Einträge werden geladen",
  "feed.loading": "Feed wird geladen",
  "feed.seeAll": "Alle ansehen",
  "feed.empty.title": "Nichts vorhanden",
  "feed.empty.message":
    "Dieser Feed enthält derzeit keine Einträge. Zum Aktualisieren nach unten ziehen.",
  "history.empty.title": "Noch nichts angesehen",
  "history.empty.message":
    "Angesehene Videos erscheinen hier, sobald der Verlauf aktiviert ist.",
  "history.title": "Verlauf",
  "channel.tab.home": "Start",
  "channel.tab.videos": "Videos",
  "channel.tab.shorts": "Shorts",
  "channel.tab.playlists": "Playlists",
  "channel.tab.about": "Info",
  "channel.loading": "Kanal wird geladen",
  "channel.error.title": "Kanal nicht verfügbar",
  "channel.error.message": "Der Kanal konnte nicht geladen werden.",
  "playlist.playAll": "Alle abspielen",
  "playlist.save": "Playlist speichern",
  "playlist.remove": "Playlist entfernen",
  "playlist.loading": "Playlist wird geladen",
  "playlist.empty.title": "Leere Playlist",
  "playlist.empty.message": "Diese Playlist enthält noch keine Videos.",
  "playlist.manager.saveVideo": "Video speichern",
  "playlist.manager.saveTo": "Hinzufügen zu…",
  "playlist.manager.saveHint": "Speichert das Video in dieser Playlist",
  "playlist.manager.name": "Name der Playlist",
  "playlist.manager.create": "Playlist erstellen",
  "playlist.manager.add": "Playlist hinzufügen",
  "playlist.manager.createError": "Playlist konnte nicht erstellt werden",
  "playlist.manager.added": "Zur Playlist hinzugefügt",
  "playlist.manager.saveError":
    "Video konnte nicht in der Playlist gespeichert werden",
  "downloads.empty.title": "Keine Downloads",
  "downloads.empty.message":
    "Heruntergeladene Videos und Musik erscheinen hier.",
  "downloads.active.empty.title": "Keine aktiven Downloads",
  "downloads.active.empty.message":
    "Neue Downloads erscheinen während der Übertragung hier.",
  "uploads.active.empty.title": "Keine aktiven Uploads",
  "uploads.active.empty.message":
    "Übertragungen an deine Watch erscheinen hier.",
  "downloads.activeAction": "Aktive Downloads anzeigen",
  "uploads.activeAction": "Aktive Uploads anzeigen",
  "downloads.upload": "Auf Watch laden",
  "downloads.remove": "Download entfernen",
  "transfer.progress": "{percent}% abgeschlossen",
  "watch.uploadStarted": "Upload zur Watch gestartet",
  "watch.uploadFailed": "Upload zur Watch fehlgeschlagen",
  "watch.playlistSent": "Playlist an die Watch gesendet",
  "watch.playlistFailed": "Playlist konnte nicht an die Watch gesendet werden",
  "watch.fileFailed": "Datei konnte nicht an die Watch gesendet werden",
  "watch.uploadComplete": "Auf die Watch geladen",
  "watchLibrary.connection.reachable": "Verbunden",
  "watchLibrary.connection.unreachable": "Nicht erreichbar",
  "watchLibrary.lastSync": "Aktualisiert {time}",
  "watchLibrary.neverSynced": "Noch nicht synchronisiert",
  "watchLibrary.waiting": "Warte auf die Uhr …",
  "watchLibrary.outdated":
    "Auf der Uhr gibt es neuere Änderungen. Sie erscheinen, sobald die Watch-App ihren Bestand sendet.",
  "watchLibrary.refresh": "Aktualisieren",
  "watchLibrary.storage.title": "Speicher",
  "watchLibrary.storage.summary":
    "{used} durch Downloads belegt · {available} frei",
  "watchLibrary.storage.accessibility":
    "Downloads belegen {percent} % des verfügbaren Speichers der Uhr",
  "watchLibrary.tabs.downloads": "Downloads ({count})",
  "watchLibrary.tabs.playlists": "Playlists ({count})",
  "watchLibrary.untitled": "Unbekannter Titel",
  "watchLibrary.download.queued": "In Warteschlange",
  "watchLibrary.download.progress": "{percent} %",
  "watchLibrary.playlist.summary": "{count} Titel · {downloaded} geladen",
  "watchLibrary.playlist.autoDownload": "Lädt neue Titel automatisch",
  "watchLibrary.downloads.empty.title": "Keine Downloads auf der Uhr",
  "watchLibrary.downloads.empty.message":
    "Auf der Uhr geladene Titel erscheinen hier.",
  "watchLibrary.playlists.empty.title": "Keine Playlists auf der Uhr",
  "watchLibrary.playlists.empty.message":
    "An die Uhr gesendete Playlists erscheinen hier.",
  "watchLibrary.noSnapshot.title": "Noch keine Daten von der Uhr",
  "watchLibrary.noSnapshot.message":
    "Öffne ReactTube auf deiner Apple Watch, damit sie ihren Bestand melden kann.",
  "watchLibrary.unavailable.title": "Watch-App nicht installiert",
  "watchLibrary.unavailable.message":
    "Installiere ReactTube auf deiner Apple Watch, um sie von hier aus zu verwalten.",
  "watchLibrary.action.deleteDownload": "Von der Uhr löschen",
  "watchLibrary.action.cancelDownload": "Download abbrechen",
  "watchLibrary.action.downloadPlaylist": "Alle Titel auf der Uhr laden",
  "watchLibrary.action.deletePlaylistDownloads":
    "Downloads dieser Playlist löschen",
  "watchLibrary.action.clearAll": "Alle löschen",
  "watchLibrary.clearAll.title": "Alle Downloads auf der Uhr löschen?",
  "watchLibrary.clearAll.message":
    "Playlists bleiben auf der Uhr. Titel können später erneut geladen werden.",
  "watchLibrary.pendingOp.downloadVideos": "Download ausstehend",
  "watchLibrary.pendingOp.cancelDownloads": "Abbruch ausstehend",
  "watchLibrary.pendingOp.deleteDownload": "Löschen ausstehend",
  "watchLibrary.pendingOp.removeVideos": "Entfernen ausstehend",
  "watchLibrary.pending.title": "Ausstehende Änderungen",
  "watchLibrary.command.downloadVideos": "{count} Titel auf der Uhr laden",
  "watchLibrary.command.cancelDownloads": "{count} Downloads abbrechen",
  "watchLibrary.command.deleteDownload": "{count} Downloads löschen",
  "watchLibrary.command.removeVideos": "{count} Titel entfernen",
  "watchLibrary.command.clearAllDownloads": "Alle Downloads löschen",
  "watchLibrary.command.other": "Bestand der Uhr ändern",
  "watchLibrary.state.pending":
    "Wird ausgeführt, sobald die Watch-App aktiv ist · gesendet {time}",
  "watchLibrary.state.stale":
    "Keine Antwort der Uhr seit {time}. Öffne ReactTube auf deiner Uhr.",
  "watchLibrary.state.applied": "Erledigt · warte auf Aktualisierung der Uhr",
  "watchLibrary.state.failed": "Fehlgeschlagen",
  "watchLibrary.state.failedWithReason": "Fehlgeschlagen: {reason}",
  "watchLibrary.state.unsupported":
    "Die Watch-App unterstützt das noch nicht. Bitte aktualisiere sie.",
  "watchLibrary.retry": "Erneut senden",
  "watchLibrary.discard": "Verwerfen",
  "sponsorBlock.skipping": "{category} wird übersprungen",
  "menu.channel": "Kanal öffnen",
  "search.empty.title": "YouTube durchsuchen",
  "search.empty.message":
    "Gib einen Suchbegriff ein, um Videos, Kanäle und Playlists zu sehen.",
  "search.music.empty.title": "YouTube Music durchsuchen",
  "search.music.empty.message":
    "Gib einen Suchbegriff ein, um Titel, Künstler, Alben und Playlists zu finden.",
  "search.noResults.title": "Keine Treffer",
  "search.noResults.message":
    "Kein Eintrag passt zu diesem Suchbegriff. Versuche eine andere Formulierung.",
  "search.placeholder": "Suchen",
  "demo.title": "UI-Bausteine",
  "demo.subtitle": "Beispiele für Theme, Schrift, Interaktion und Zustände",
  "demo.actions": "Aktionen",
  "demo.primaryAction": "Primäre Aktion",
  "demo.secondaryAction": "Sekundäre Aktion",
  "demo.iconAction": "Weitere Optionen öffnen",
  "demo.filters": "Filter",
  "demo.filter.all": "Alle",
  "demo.filter.videos": "Videos",
  "demo.filter.music": "Musik",
  "demo.states": "Zustände",
  "demo.loading": "Vorschau wird geladen",
  "demo.languageAction": "Sprache wechseln",
  "video.upNext": "Als Nächstes",
  "video.playlist": "Playlist",
  "video.related": "Ähnliche Videos",
  "video.chapters": "Kapitel",
  "video.chapters.position": "Kapitel {index} von {total}",
  "video.chapters.nowPlaying": "Läuft gerade",
  "video.chapters.start": "Beginnt bei {time}",
  "video.chapters.accessibilityLabel": "{title}, beginnt bei {time}",
  "video.chapters.accessibilityLabelActive": "{title}, läuft gerade",
  "video.chapters.accessibilityHint": "Springt zu diesem Kapitel",
  "video.subscribe": "Abonnieren",
  "video.subscribed": "Abonniert",
  "video.action.like": "Gefällt mir",
  "video.action.dislike": "Gefällt mir nicht",
  "video.action.save": "Speichern",
  "video.action.download": "Herunterladen",
  "video.action.description": "Beschreibung",
  "video.action.comments": "Kommentare",
  "video.action.queue": "Warteschlange",
  "video.description.title": "Beschreibung",
  "video.description.empty": "Dieses Video hat keine Beschreibung.",
  "video.comments.title": "Kommentare",
  "video.comments.count": "{count} Kommentare",
  "video.comments.empty.title": "Keine Kommentare",
  "video.comments.empty.message":
    "Zu diesem Video gibt es noch keine Kommentare.",
  "video.comments.error.title": "Kommentare nicht verfügbar",
  "video.comments.error.message":
    "Die Kommentare konnten nicht geladen werden.",
  "video.comments.likes": "{count} Likes",
  "video.comments.replies": "{count} Antworten",
  "video.comments.pinned": "Angepinnt",
  "video.comments.loading": "Kommentare werden geladen",
  "video.queue.title": "Warteschlange",
  "video.queue.position": "{index} von {total}",
  "video.queue.nowPlaying": "Wird gerade abgespielt",
  "video.unavailable.title": "Video nicht verfügbar",
  "video.unavailable.message":
    "Dieses Video kann derzeit nicht abgespielt werden.",
  "video.loading": "Video wird geladen",
  "video.player.details": "Videodetails",
  "video.player.jumpToStart": "Zurück zum Anfang",
  "video.player.reload": "Stream neu laden",
  "video.player.settings": "Playereinstellungen",
  "video.player.speed": "Wiedergabegeschwindigkeit",
  "video.player.speeds": "Wiedergabegeschwindigkeiten",
  "video.player.language": "Audiosprache",
  "video.player.subtitles": "Untertitel",
  "video.player.subtitles.off": "Aus",
  "video.player.subtitles.none": "Dieses Video hat keine Untertitel.",
  "video.player.subtitles.translated":
    "{language} (automatisch übersetzt aus {source})",
  "video.player.subtitles.loadError": "Untertitel konnten nicht geladen werden",
  "video.player.subtitles.rateLimited":
    "YouTube begrenzt Untertitel-Anfragen gerade. Bitte später erneut versuchen.",
  "video.player.channel": "Kanal öffnen",
  "video.panel.close": "Panel schließen",
  "video.endscreen.browse": "Empfehlungen",
  "video.endscreen.exit": "Zurück zum Video",
  "video.endscreen.fromCreator": "Vom Kanal empfohlen",
  "video.endscreen.playlist": "Playlist",
  "video.endscreen.channel": "Kanal",
  "video.upNext.startsIn": "Startet in {seconds} s",
  "video.upNext.stopped": "Automatische Wiedergabe angehalten",
  "video.upNext.playNow": "Jetzt abspielen",
  "shorts.player.hint":
    "Spielt das Short ab oder pausiert es. Nach oben oder unten drücken für das vorherige oder nächste Short.",
  "shorts.player.paused": "Pausiert",
  "shorts.previous": "Vorheriges Short",
  "shorts.next": "Nächstes Short",
} as const satisfies Record<TranslationKey, string>;
