import type {TranslationKey} from "./en";

export const de = {
  "common.retry": "Erneut versuchen",
  "common.continue": "Weiter",
  "common.close": "Schließen",
  "navigation.home": "Start",
  "navigation.search": "Suche",
  "navigation.subscriptions": "Abos",
  "navigation.library": "Mediathek",
  "navigation.history": "Verlauf",
  "navigation.myYoutube": "Mein YouTube",
  "navigation.music": "Musik",
  "navigation.downloads": "Downloads",
  "navigation.settings": "Einstellungen",
  "navigation.login": "Anmelden",
  "navigation.video": "Video",
  "navigation.channel": "Kanal",
  "navigation.playlist": "Playlist",
  "navigation.activeDownloads": "Aktive Downloads",
  "navigation.activeUploads": "Aktive Uploads",
  "navigation.musicLibrary": "Musikmediathek",
  "navigation.musicSearch": "Musiksuche",
  "navigation.musicPlaylist": "Musikplaylist",
  "navigation.musicChannel": "Musikkanal",
  "navigation.musicPlayer": "Musikplayer",
  "settings.general": "Allgemein",
  "settings.uiLanguage": "App-Sprache",
  "settings.contentLanguage": "Sprache der YouTube-Inhalte",
  "settings.languages": "Sprachen",
  "settings.language.english": "Englisch",
  "settings.language.german": "Deutsch",
  "settings.videoPlayer": "Videoplayer",
  "settings.videoResolution": "Variante der Videoauflösung",
  "settings.historyEnabled": "Verlauf aktiviert",
  "settings.playbackDiagnostics": "Wiedergabediagnose",
  "settings.clearAll": "Alle Daten löschen",
  "settings.logout": "Abmelden",
  "settings.value.true": "Ein",
  "settings.value.false": "Aus",
  "state.empty.title": "Noch keine Inhalte",
  "state.empty.message": "Verfügbare Inhalte werden hier angezeigt.",
  "state.error.title": "Etwas ist schiefgelaufen",
  "state.error.message": "Der Inhalt konnte nicht geladen werden.",
  "demo.title": "UI-Bausteine",
  "demo.subtitle": "Beispiele für Theme, Schrift, Interaktion und Zustände",
  "demo.actions": "Aktionen",
  "demo.primaryAction": "Primäre Aktion",
  "demo.secondaryAction": "Sekundäre Aktion",
  "demo.iconAction": "Weitere Optionen öffnen",
  "demo.filters": "Filter",
  "demo.filter.all": "Alle",
  "demo.filter.videos": "Videos",
  "demo.filter.music": "Musik",
  "demo.states": "Zustände",
  "demo.loading": "Vorschau wird geladen",
  "demo.languageAction": "Sprache wechseln",
} as const satisfies Record<TranslationKey, string>;
