import type {TranslationKey} from "./en";

export const de = {
  "common.retry": "Erneut versuchen",
  "common.continue": "Weiter",
  "common.close": "Schließen",
  "common.back": "Zurück",
  "navigation.home": "Start",
  "navigation.search": "Suche",
  "navigation.subscriptions": "Abos",
  "navigation.library": "Mediathek",
  "navigation.history": "Verlauf",
  "navigation.myYoutube": "Mein YouTube",
  "navigation.music": "Musik",
  "navigation.downloads": "Downloads",
  "navigation.settings": "Einstellungen",
  "navigation.login": "Anmelden",
  "navigation.you": "Du",
  "navigation.account": "Konto",
  "navigation.video": "Video",
  "navigation.channel": "Kanal",
  "navigation.playlists": "Playlists",
  "navigation.playlist": "Playlist",
  "navigation.activeDownloads": "Aktive Downloads",
  "navigation.activeUploads": "Aktive Uploads",
  "navigation.musicLibrary": "Musikmediathek",
  "navigation.musicSearch": "Musiksuche",
  "navigation.musicPlaylist": "Musikplaylist",
  "navigation.musicChannel": "Musikkanal",
  "navigation.musicPlayer": "Musikplayer",
  "settings.general": "Allgemein",
  "settings.uiLanguage": "App-Sprache",
  "settings.contentLanguage": "Sprache der YouTube-Inhalte",
  "settings.languages": "Sprachen",
  "settings.language.english": "Englisch",
  "settings.language.german": "Deutsch",
  "settings.videoPlayer": "Videoplayer",
  "settings.videoResolution": "Variante der Videoauflösung",
  "settings.historyEnabled": "Verlauf aktiviert",
  "settings.playbackDiagnostics": "Wiedergabediagnose",
  "settings.clearAll": "Alle Daten löschen",
  "settings.logout": "Abmelden",
  "settings.value.true": "Ein",
  "settings.value.false": "Aus",
  "you.account": "Konto",
  "you.signedIn": "Du bist angemeldet",
  "you.signedOut.title": "Nicht angemeldet",
  "you.signedOut.message":
    "Melde dich an, um Abos, Verlauf und Mediathek zu nutzen.",
  "you.content": "Deine Inhalte",
  "you.app": "App",
  "subscriptions.signedOut.title": "Abos brauchen ein Konto",
  "subscriptions.signedOut.message":
    "Melde dich an, um Kanälen zu folgen und neue Videos hier zu sehen.",
  "navigationRail.expand": "Navigation öffnen",
  "navigationRail.collapse": "Navigation schließen",
  "music.loading": "Titel wird geladen",
  "music.play": "Abspielen",
  "music.pause": "Pause",
  "state.empty.title": "Noch keine Inhalte",
  "state.empty.message": "Verfügbare Inhalte werden hier angezeigt.",
  "state.error.title": "Etwas ist schiefgelaufen",
  "state.error.message": "Der Inhalt konnte nicht geladen werden.",
  "media.videoCount": "{count} Videos",
  "media.badge.live": "Live",
  "media.badge.mix": "Mix",
  "media.badge.downloaded": "Heruntergeladen",
  "media.progress": "{percent}% angesehen",
  "media.hint.video": "Öffnet das Video",
  "media.hint.playlist": "Öffnet die Playlist",
  "media.hint.channel": "Öffnet den Kanal",
  "media.thumbnailUnavailable": "Vorschaubild nicht verfügbar",
  "media.moreOptions": "Weitere Optionen",
  "feed.refresh": "Aktualisieren",
  "feed.loadingMore": "Weitere Einträge werden geladen",
  "feed.loading": "Feed wird geladen",
  "feed.seeAll": "Alle ansehen",
  "feed.empty.title": "Nichts vorhanden",
  "feed.empty.message":
    "Dieser Feed enthält derzeit keine Einträge. Zum Aktualisieren nach unten ziehen.",
  "history.empty.title": "Noch nichts angesehen",
  "history.empty.message":
    "Angesehene Videos erscheinen hier, sobald der Verlauf aktiviert ist.",
  "history.title": "Verlauf",
  "search.empty.title": "YouTube durchsuchen",
  "search.empty.message":
    "Gib einen Suchbegriff ein, um Videos, Kanäle und Playlists zu sehen.",
  "search.noResults.title": "Keine Treffer",
  "search.noResults.message":
    "Kein Eintrag passt zu diesem Suchbegriff. Versuche eine andere Formulierung.",
  "search.placeholder": "Suchen",
  "demo.title": "UI-Bausteine",
  "demo.subtitle": "Beispiele für Theme, Schrift, Interaktion und Zustände",
  "demo.actions": "Aktionen",
  "demo.primaryAction": "Primäre Aktion",
  "demo.secondaryAction": "Sekundäre Aktion",
  "demo.iconAction": "Weitere Optionen öffnen",
  "demo.filters": "Filter",
  "demo.filter.all": "Alle",
  "demo.filter.videos": "Videos",
  "demo.filter.music": "Musik",
  "demo.states": "Zustände",
  "demo.loading": "Vorschau wird geladen",
  "demo.languageAction": "Sprache wechseln",
  "video.upNext": "Als Nächstes",
  "video.related": "Ähnliche Videos",
  "video.chapters": "Kapitel",
  "video.subscribe": "Abonnieren",
  "video.subscribed": "Abonniert",
  "video.action.like": "Gefällt mir",
  "video.action.dislike": "Gefällt mir nicht",
  "video.action.save": "Speichern",
  "video.action.download": "Herunterladen",
  "video.action.description": "Beschreibung",
  "video.action.comments": "Kommentare",
  "video.action.queue": "Warteschlange",
  "video.description.title": "Beschreibung",
  "video.description.empty": "Dieses Video hat keine Beschreibung.",
  "video.comments.title": "Kommentare",
  "video.comments.count": "{count} Kommentare",
  "video.comments.empty.title": "Keine Kommentare",
  "video.comments.empty.message":
    "Zu diesem Video gibt es noch keine Kommentare.",
  "video.comments.error.title": "Kommentare nicht verfügbar",
  "video.comments.error.message":
    "Die Kommentare konnten nicht geladen werden.",
  "video.comments.likes": "{count} Likes",
  "video.comments.replies": "{count} Antworten",
  "video.comments.pinned": "Angepinnt",
  "video.comments.loading": "Kommentare werden geladen",
  "video.queue.title": "Warteschlange",
  "video.queue.position": "{index} von {total}",
  "video.queue.nowPlaying": "Wird gerade abgespielt",
  "video.unavailable.title": "Video nicht verfügbar",
  "video.unavailable.message":
    "Dieses Video kann derzeit nicht abgespielt werden.",
  "video.loading": "Video wird geladen",
  "video.player.details": "Videodetails",
  "video.player.jumpToStart": "Zurück zum Anfang",
  "video.player.reload": "Stream neu laden",
  "video.player.settings": "Playereinstellungen",
  "video.player.channel": "Kanal öffnen",
  "video.panel.close": "Panel schließen",
} as const satisfies Record<TranslationKey, string>;
