export const en = {
  "common.retry": "Try again",
  "common.continue": "Continue",
  "common.close": "Close",
  "common.back": "Back",
  "navigation.home": "Home",
  "navigation.search": "Search",
  "navigation.subscriptions": "Subscriptions",
  "navigation.library": "Library",
  "navigation.history": "History",
  "navigation.myYoutube": "My YouTube",
  "navigation.music": "Music",
  "navigation.downloads": "Downloads",
  "navigation.settings": "Settings",
  "navigation.login": "Sign in",
  "navigation.you": "You",
  "navigation.account": "Account",
  "navigation.video": "Video",
  "navigation.channel": "Channel",
  "navigation.playlists": "Playlists",
  "navigation.playlist": "Playlist",
  "navigation.activeDownloads": "Active downloads",
  "navigation.activeUploads": "Active uploads",
  "navigation.musicLibrary": "Music library",
  "navigation.musicSearch": "Music search",
  "navigation.musicPlaylist": "Music playlist",
  "navigation.musicChannel": "Music channel",
  "navigation.musicPlayer": "Music player",
  "settings.general": "General",
  "settings.uiLanguage": "App language",
  "settings.contentLanguage": "YouTube content language",
  "settings.languages": "Languages",
  "settings.language.english": "English",
  "settings.language.german": "German",
  "settings.videoPlayer": "Video player",
  "settings.videoResolution": "Video resolution variant",
  "settings.historyEnabled": "History enabled",
  "settings.playbackDiagnostics": "Playback diagnostics",
  "settings.clearAll": "Clear all",
  "settings.logout": "Sign out",
  "settings.value.true": "On",
  "settings.value.false": "Off",
  "you.account": "Account",
  "you.signedIn": "You are signed in",
  "you.signedOut.title": "Not signed in",
  "you.signedOut.message":
    "Sign in to use your subscriptions, history, and library.",
  "you.content": "Your content",
  "you.app": "App",
  "subscriptions.signedOut.title": "Subscriptions need an account",
  "subscriptions.signedOut.message":
    "Sign in to follow channels and see their new videos here.",
  "navigationRail.expand": "Open navigation",
  "navigationRail.collapse": "Close navigation",
  "music.loading": "Loading track",
  "music.play": "Play",
  "music.pause": "Pause",
  "state.empty.title": "Nothing here yet",
  "state.empty.message": "Content will appear here when it is available.",
  "state.error.title": "Something went wrong",
  "state.error.message": "The content could not be loaded.",
  "media.videoCount": "{count} videos",
  "media.badge.live": "Live",
  "media.badge.mix": "Mix",
  "media.badge.downloaded": "Downloaded",
  "media.progress": "{percent}% watched",
  "media.hint.video": "Opens the video",
  "media.hint.playlist": "Opens the playlist",
  "media.hint.channel": "Opens the channel",
  "media.thumbnailUnavailable": "Preview image unavailable",
  "media.moreOptions": "More options",
  "feed.refresh": "Refresh",
  "feed.loadingMore": "Loading more entries",
  "feed.loading": "Loading feed",
  "feed.seeAll": "See all",
  "feed.empty.title": "Nothing to show",
  "feed.empty.message":
    "This feed has no entries right now. Pull down to refresh.",
  "history.empty.title": "Nothing watched yet",
  "history.empty.message":
    "Videos you watch appear here once history is enabled.",
  "history.title": "History",
  "search.empty.title": "Search YouTube",
  "search.empty.message":
    "Enter a search term to see videos, channels, and playlists.",
  "search.noResults.title": "No results",
  "search.noResults.message":
    "No entry matches this search term. Try a different wording.",
  "search.placeholder": "Search",
  "demo.title": "UI building blocks",
  "demo.subtitle": "Theme, type, interaction, and state examples",
  "demo.actions": "Actions",
  "demo.primaryAction": "Primary action",
  "demo.secondaryAction": "Secondary action",
  "demo.iconAction": "Open more options",
  "demo.filters": "Filters",
  "demo.filter.all": "All",
  "demo.filter.videos": "Videos",
  "demo.filter.music": "Music",
  "demo.states": "States",
  "demo.loading": "Loading preview",
  "demo.languageAction": "Change language",
} as const;

export type TranslationKey = keyof typeof en;
