export const en = {
  "common.retry": "Try again",
  "common.cancel": "Cancel",
  "common.continue": "Continue",
  "common.close": "Close",
  "common.back": "Back",
  "common.remove": "Remove",
  "common.save": "Save",
  "common.saved": "Saved",
  "common.copy": "Copy",
  "common.enabled": "Enabled",
  "common.disabled": "Disabled",
  "common.loading": "Loading",
  "common.more": "More",
  "navigation.home": "Home",
  "navigation.search": "Search",
  "navigation.subscriptions": "Subscriptions",
  "navigation.library": "Library",
  "navigation.history": "History",
  "navigation.myYoutube": "My YouTube",
  "navigation.music": "Music",
  "navigation.downloads": "Downloads",
  "navigation.settings": "Settings",
  "navigation.login": "Sign in",
  "navigation.you": "You",
  "navigation.account": "Account",
  "navigation.video": "Video",
  "navigation.channel": "Channel",
  "navigation.playlists": "Playlists",
  "navigation.playlist": "Playlist",
  "navigation.activeDownloads": "Active downloads",
  "navigation.watchLibrary": "Apple Watch",
  "navigation.musicLibrary": "Music library",
  "navigation.musicSearch": "Music search",
  "navigation.musicPlaylist": "Music playlist",
  "navigation.musicChannel": "Music channel",
  "navigation.musicPlayer": "Music player",
  "settings.general": "General",
  "settings.uiLanguage": "App language",
  "settings.contentLanguage": "YouTube content language",
  "settings.languages": "Languages",
  "settings.language.english": "English",
  "settings.language.german": "German",
  "settings.videoPlayer": "Video player",
  "settings.videoResolution": "Video resolution variant",
  "settings.historyEnabled": "History enabled",
  "settings.playbackDiagnostics": "Playback diagnostics",
  "settings.playerTypes": "Player types",
  "settings.videoTracking": "Video tracking",
  "settings.player.native": "Native",
  "settings.player.nativeOverlay": "Native overlay (experimental)",
  "settings.player.vlc": "VLC",
  "settings.resolution.localHls": "Local HLS — up to 1080p, multilingual",
  "settings.resolution.localHlsAv1":
    "Local HLS + AV1 — 4K (Apple TV 4K, 3rd generation only)",
  "settings.resolution.youtubeHls":
    "YouTube HLS — up to 1080p, mixed audio (default)",
  "settings.resolution.progressive": "Progressive (may stop early)",
  "settings.resolution.sabr": "SABR (experimental — falls back automatically)",
  "settings.diagnostics.run": "Run diagnostics",
  "settings.diagnostics.running": "Running…",
  "settings.diagnostics.sessionUnavailable":
    "Innertube session is not ready yet.",
  "settings.diagnostics.hint":
    "Checks the JavaScript engine, player, clients, and SABR segment retrieval with a test video. Run this in a release build because debug builds can use a different engine.",
  "settings.clearAll": "Clear all",
  "settings.logout": "Sign out",
  "settings.channel": "Channel",
  "settings.channel.title": "Channels",
  "settings.channel.primaryAccount": "Primary account",
  "settings.channel.brandChannel": "Brand channel",
  "settings.channel.loading": "Loading channels",
  "settings.channel.loadFailed": "Channels could not be loaded.",
  "settings.channel.signedOut": "Sign in to choose a channel.",
  "settings.channel.noChoice":
    "This sign-in belongs to {name} only. To watch age-restricted videos and switch between your channels, sign out and sign in again with your primary Google account.",
  "settings.channel.hint":
    "The app acts as the selected channel, as in the browser. Age-restricted videos keep working because the primary account stays signed in.",
  "settings.loudnessNormalization": "Normalize music volume",
  "settings.loudness.off": "Off",
  "settings.loudness.standard": "Standard (default)",
  "settings.loudness.strong": "Strong — more headroom for quiet songs",
  "settings.loudness.hint":
    "Uses YouTube loudness data to play loud songs more quietly. Songs can only be turned down, so the overall volume drops slightly; raise the device volume once to compensate.",
  "settings.value.true": "On",
  "settings.value.false": "Off",
  "you.account": "Account",
  "you.signedIn": "You are signed in",
  "you.signedOut.title": "Not signed in",
  "you.signedOut.message":
    "Sign in to use your subscriptions, history, and library.",
  "you.content": "Your content",
  "you.app": "App",
  "subscriptions.signedOut.title": "Subscriptions need an account",
  "subscriptions.signedOut.message":
    "Sign in to follow channels and see their new videos here.",
  "login.code": "Your code is {code}",
  "login.waiting.title": "Ready to sign in",
  "login.waiting.message": "Start sign-in to request a device code.",
  "login.start": "Start sign-in",
  "login.openPage": "Open sign-in page",
  "login.success": "Signed in successfully",
  "navigationRail.expand": "Open navigation",
  "navigationRail.collapse": "Close navigation",
  "music.loading": "Loading track",
  "music.play": "Play",
  "music.pause": "Pause",
  "music.library.empty.title": "Your music library is empty",
  "music.library.empty.message":
    "Saved albums, playlists, and downloaded music appear here.",
  "music.playAll": "Play all",
  "music.startRadio": "Start radio",
  "music.save": "Save",
  "music.unsave": "Remove from library",
  "music.song": "Song",
  "music.video": "Video",
  "music.author": "Artist",
  "music.queue": "Up next",
  "music.lyrics": "Lyrics",
  "music.related": "Related",
  "music.downloadStarted": "Download started",
  "music.downloadComplete": "Download complete",
  "music.downloadFailed": "Download failed",
  "music.addToPlaylist": "Add to playlist",
  "music.playNext": "Play next",
  "music.previous": "Previous track",
  "music.next": "Next track",
  "music.repeat": "Repeat",
  "music.shuffle": "Shuffle",
  "music.autoplay": "Autoplay {state}",
  "music.autoplay.hint": "Add similar songs for continuous playback.",
  "music.openArtist": "Open artist",
  "music.error.loading": "Error loading track",
  "music.error.reload": "Could not reload track",
  "music.error.unavailable": "Track cannot be played",
  "music.error.noSource": "No playable audio source is available.",
  "music.error.playbackFailed": "Playback failed",
  "music.error.playbackInterrupted": "Playback interrupted",
  "music.error.retrying": "{message} Retrying once…",
  "state.empty.title": "Nothing here yet",
  "state.empty.message": "Content will appear here when it is available.",
  "state.error.title": "Something went wrong",
  "state.error.message": "The content could not be loaded.",
  "database.error.title": "Local database could not be prepared",
  "database.error.message":
    "The download database could not be migrated. You can try again, repair the database or reset it.",
  "database.error.repairing": "Database is being repaired…",
  "database.action.retry": "Try again",
  "database.action.repair": "Repair database",
  "database.action.reset": "Reset database",
  "database.action.details": "Show details",
  "database.action.hideDetails": "Hide details",
  "database.action.copyDetails": "Copy details",
  "database.repair.hint":
    "Repairing rebuilds the database and keeps as much information as possible. Resetting deletes all playlist and download information; downloaded files stay on the device.",
  "database.reset.confirmTitle": "Reset database?",
  "database.reset.confirmMessage":
    "All local playlist and download information will be deleted. This cannot be undone.",
  "database.recovered": "The local database had to be repaired on startup.",
  "media.videoCount": "{count} videos",
  "media.badge.live": "Live",
  "media.badge.mix": "Mix",
  "media.badge.downloaded": "Downloaded",
  "media.badge.4k": "4K",
  "media.badge.8k": "8K",
  "media.progress": "{percent}% watched",
  "media.hint.video": "Opens the video",
  "media.hint.playlist": "Opens the playlist",
  "media.hint.channel": "Opens the channel",
  "media.thumbnailUnavailable": "Preview image unavailable",
  "media.moreOptions": "More options",
  "feed.refresh": "Refresh",
  "feed.loadingMore": "Loading more entries",
  "feed.loading": "Loading feed",
  "feed.seeAll": "See all",
  "feed.empty.title": "Nothing to show",
  "feed.empty.message":
    "This feed has no entries right now. Pull down to refresh.",
  "history.empty.title": "Nothing watched yet",
  "history.empty.message":
    "Videos you watch appear here once history is enabled.",
  "history.title": "History",
  "channel.tab.home": "Home",
  "channel.tab.videos": "Videos",
  "channel.tab.shorts": "Shorts",
  "channel.tab.playlists": "Playlists",
  "channel.tab.about": "About",
  "channel.loading": "Loading channel",
  "channel.error.title": "Channel unavailable",
  "channel.error.message": "The channel could not be loaded.",
  "playlist.playAll": "Play all",
  "playlist.save": "Save playlist",
  "playlist.remove": "Remove playlist",
  "playlist.loading": "Loading playlist",
  "playlist.empty.title": "Empty playlist",
  "playlist.empty.message": "This playlist does not contain any videos yet.",
  "playlist.manager.saveVideo": "Save video",
  "playlist.manager.saveTo": "Save to…",
  "playlist.manager.saveHint": "Saves the video to this playlist",
  "playlist.manager.name": "Playlist name",
  "playlist.manager.create": "Create playlist",
  "playlist.manager.add": "Add playlist",
  "playlist.manager.created": "Playlist created",
  "playlist.manager.createError": "Could not create playlist",
  "playlist.manager.added": "Added to playlist",
  "playlist.manager.saveError": "Could not save the video to the playlist",
  "downloads.empty.title": "No downloads",
  "downloads.empty.message": "Downloaded videos and music appear here.",
  "downloads.active.empty.title": "No active downloads",
  "downloads.active.empty.message":
    "New downloads appear here while they transfer.",
  "downloads.activeAction": "Show active downloads",
  "downloads.upload": "Transfer to Watch",
  "downloads.remove": "Remove download",
  "transfer.progress": "{percent}% complete",
  "watch.uploadStarted": "Transfer to the Watch started",
  "watch.uploadFailed": "This title cannot be transferred to the Watch",
  "watchLibrary.connection.reachable": "Connected",
  "watchLibrary.connection.unreachable": "Not reachable",
  "watchLibrary.lastSync": "Updated {time}",
  "watchLibrary.neverSynced": "Not synced yet",
  "watchLibrary.waiting": "Waiting for the Watch…",
  "watchLibrary.outdated":
    "The Watch has newer changes. They appear once the Watch app sends its library.",
  "watchLibrary.refresh": "Refresh",
  "watchLibrary.storage.title": "Storage",
  "watchLibrary.storage.summary": "{used} used by downloads · {available} free",
  "watchLibrary.storage.accessibility":
    "Downloads use {percent}% of the available Watch storage",
  "watchLibrary.tabs.downloads": "Downloads ({count})",
  "watchLibrary.tabs.playlists": "Playlists ({count})",
  "watchLibrary.untitled": "Unknown title",
  "watchLibrary.download.queued": "Queued",
  "watchLibrary.download.progress": "{percent}%",
  "watchLibrary.playlist.summary": "{count} titles · {downloaded} downloaded",
  "watchLibrary.playlist.autoDownload": "Downloads new titles automatically",
  "watchLibrary.downloads.empty.title": "No downloads on the Watch",
  "watchLibrary.downloads.empty.message":
    "Titles downloaded on the Watch appear here.",
  "watchLibrary.playlists.empty.title": "No playlists on the Watch",
  "watchLibrary.playlists.empty.message":
    "Playlists sent to the Watch appear here.",
  "watchLibrary.noSnapshot.title": "No data from the Watch yet",
  "watchLibrary.noSnapshot.message":
    "Open ReactTube on your Apple Watch so it can report its library.",
  "watchLibrary.unavailable.title": "Watch app not installed",
  "watchLibrary.unavailable.message":
    "Install ReactTube on your Apple Watch to manage it from here.",
  "watchLibrary.action.deleteDownload": "Delete from Watch",
  "watchLibrary.action.cancelDownload": "Cancel download",
  "watchLibrary.action.deletePlaylistDownloads":
    "Delete downloads of this playlist",
  "watchLibrary.action.clearAll": "Delete all",
  "watchLibrary.clearAll.title": "Delete all downloads on the Watch?",
  "watchLibrary.clearAll.message":
    "Playlists stay on the Watch. Titles can be downloaded again later.",
  "watchLibrary.pendingOp.downloadVideos": "Download pending",
  "watchLibrary.pendingOp.cancelDownloads": "Cancellation pending",
  "watchLibrary.pendingOp.deleteDownload": "Deletion pending",
  "watchLibrary.pendingOp.removeVideos": "Removal pending",
  "watchLibrary.pending.title": "Pending changes",
  "watchLibrary.command.downloadVideos": "Download {count} titles on the Watch",
  "watchLibrary.command.cancelDownloads": "Cancel {count} downloads",
  "watchLibrary.command.deleteDownload": "Delete {count} downloads",
  "watchLibrary.command.removeVideos": "Remove {count} titles",
  "watchLibrary.command.clearAllDownloads": "Delete all downloads",
  "watchLibrary.command.other": "Change the Watch library",
  "watchLibrary.state.pending":
    "Runs once the Watch app is active · sent {time}",
  "watchLibrary.state.stale":
    "No answer from the Watch since {time}. Open ReactTube on your Watch.",
  "watchLibrary.state.applied": "Done · waiting for an update from the Watch",
  "watchLibrary.state.failed": "Failed",
  "watchLibrary.state.failedWithReason": "Failed: {reason}",
  "watchLibrary.state.unsupported":
    "The Watch app does not support this yet. Please update it.",
  "watchLibrary.retry": "Send again",
  "watchLibrary.discard": "Discard",
  "watchLibrary.link.add": "Save on Apple Watch",
  "watchLibrary.link.autoDownload": "Download automatically on Watch",
  "watchLibrary.link.autoDownloadOn": "Turn on automatic downloads",
  "watchLibrary.link.autoDownloadOff": "Turn off automatic downloads",
  "watchLibrary.link.remove": "Remove from Apple Watch",
  "watchLibrary.link.status.synced": "In sync with iPhone",
  "watchLibrary.link.status.waitingForWatch": "Waiting for the Watch",
  "watchLibrary.link.status.waitingForPhone": "Applying Watch changes",
  "watchLibrary.link.status.waitingForYouTube": "Waiting for YouTube",
  "watchLibrary.link.status.failed": "Sync failed",
  "watchLibrary.unlink.title": "Remove playlist from the Watch?",
  "watchLibrary.unlink.message":
    "The playlist stays on your iPhone. Downloads other playlists still use are kept.",
  "watchLibrary.unlink.keepDownloads": "Remove playlist only",
  "watchLibrary.unlink.deleteDownloads": "Remove with downloads",
  "watchLibrary.action.removePlaylist": "Remove from Watch",
  "watchLibrary.command.upsertPlaylist": "Update playlist on the Watch",
  "watchLibrary.command.deletePlaylist": "Remove playlist from the Watch",
  "watchLibrary.command.setPlaylistAutoDownload": "Change automatic downloads",
  "watchLibrary.transfersAction": "Show transfers to the Watch",
  "watchLibrary.tabs.transfers": "Transfers ({count})",
  "watchLibrary.transfers.empty.title": "No transfers running",
  "watchLibrary.transfers.empty.message":
    "Files sent from the iPhone and downloads on the Watch appear here.",
  "watchLibrary.transfer.fromPhone": "From iPhone",
  "watchLibrary.transfer.onWatch": "Downloading on the Watch",
  "watchLibrary.transfer.paused": "Paused",
  "watchLibrary.action.transferFromPhone": "Transfer from iPhone",
  "watchLibrary.action.transferPlaylist": "Transfer {count} titles from iPhone",
  "watchLibrary.action.downloadPlaylistOnWatch":
    "Download {count} titles on the Watch",
  "watchLibrary.pendingOp.transferVideo": "Transfer pending",
  "watchLibrary.command.transferVideo": "Transfer {count} titles from iPhone",
  "watchLibrary.sort.title": "Sort downloads",
  "watchLibrary.sort.label": "Sort: {mode}",
  "watchLibrary.sort.added": "Date added",
  "watchLibrary.sort.name": "Name",
  "watchLibrary.sort.size": "Size",
  "watchLibrary.download.added": "Added {date}",
  "watchLibrary.select.start": "Select",
  "watchLibrary.select.count": "{count} selected",
  "watchLibrary.select.all": "Select all",
  "watchLibrary.select.done": "Done",
  "watchLibrary.select.delete": "Remove ({count})",
  "watchLibrary.select.confirmTitle": "Remove {count} titles from the Watch?",
  "watchLibrary.select.confirmMessage":
    "Finished downloads are deleted, running ones are cancelled.",
  "watchLibrary.action.selectMultiple": "Select multiple",
  "watchLibrary.swipe.delete": "Delete",
  "watchLibrary.swipe.stop": "Stop",
  "sponsorBlock.skipping": "Skipping {category}",
  "menu.channel": "Open channel",
  "search.empty.title": "Search YouTube",
  "search.empty.message":
    "Enter a search term to see videos, channels, and playlists.",
  "search.music.empty.title": "Search YouTube Music",
  "search.music.empty.message":
    "Enter a search term to find songs, artists, albums, and playlists.",
  "search.noResults.title": "No results",
  "search.noResults.message":
    "No entry matches this search term. Try a different wording.",
  "search.placeholder": "Search",
  "demo.title": "UI building blocks",
  "demo.subtitle": "Theme, type, interaction, and state examples",
  "demo.actions": "Actions",
  "demo.primaryAction": "Primary action",
  "demo.secondaryAction": "Secondary action",
  "demo.iconAction": "Open more options",
  "demo.filters": "Filters",
  "demo.filter.all": "All",
  "demo.filter.videos": "Videos",
  "demo.filter.music": "Music",
  "demo.states": "States",
  "demo.loading": "Loading preview",
  "demo.languageAction": "Change language",
  "video.upNext": "Up next",
  "video.playlist": "Playlist",
  "video.related": "Related videos",
  "video.chapters": "Chapters",
  "video.chapters.position": "Chapter {index} of {total}",
  "video.chapters.nowPlaying": "Now playing",
  "video.chapters.start": "Starts at {time}",
  "video.chapters.accessibilityLabel": "{title}, starts at {time}",
  "video.chapters.accessibilityLabelActive": "{title}, now playing",
  "video.chapters.accessibilityHint": "Jumps to this chapter",
  "video.subscribe": "Subscribe",
  "video.subscribed": "Subscribed",
  "video.action.like": "Like",
  "video.action.dislike": "Dislike",
  "video.action.save": "Save",
  "video.action.download": "Download",
  "video.action.description": "Description",
  "video.action.comments": "Comments",
  "video.action.queue": "Queue",
  "video.description.title": "Description",
  "video.description.empty": "This video has no description.",
  "video.comments.title": "Comments",
  "video.comments.count": "{count} comments",
  "video.comments.empty.title": "No comments",
  "video.comments.empty.message": "Nobody has commented on this video yet.",
  "video.comments.error.title": "Comments unavailable",
  "video.comments.error.message": "The comments could not be loaded.",
  "video.comments.likes": "{count} likes",
  "video.comments.replies": "{count} replies",
  "video.comments.pinned": "Pinned",
  "video.comments.loading": "Loading comments",
  "video.queue.title": "Queue",
  "video.queue.position": "{index} of {total}",
  "video.queue.nowPlaying": "Now playing",
  "video.unavailable.title": "Video unavailable",
  "video.unavailable.message": "This video cannot be played right now.",
  "video.loading": "Loading video",
  "video.player.details": "Video details",
  "video.player.jumpToStart": "Back to start",
  "video.player.reload": "Reload stream",
  "video.player.settings": "Player settings",
  "video.player.speed": "Playback speed",
  "video.player.speeds": "Playback speeds",
  "video.player.language": "Audio language",
  "video.player.subtitles": "Subtitles",
  "video.player.subtitles.off": "Off",
  "video.player.subtitles.none": "This video has no subtitles.",
  "video.player.subtitles.translated":
    "{language} (auto-translated from {source})",
  "video.player.subtitles.loadError": "Subtitles could not be loaded",
  "video.player.subtitles.rateLimited":
    "YouTube is limiting subtitle requests right now. Try again later.",
  "video.player.channel": "Open channel",
  "video.panel.close": "Close panel",
  "video.endscreen.browse": "Recommendations",
  "video.endscreen.exit": "Back to video",
  "video.endscreen.fromCreator": "From the channel",
  "video.endscreen.playlist": "Playlist",
  "video.endscreen.channel": "Channel",
  "video.upNext.startsIn": "Starts in {seconds} s",
  "video.upNext.stopped": "Autoplay stopped",
  "video.upNext.playNow": "Play now",
  "shorts.player.hint":
    "Plays or pauses the short. Press up or down for the previous or next short.",
  "shorts.player.paused": "Paused",
  "shorts.previous": "Previous short",
  "shorts.next": "Next short",
} as const;

export type TranslationKey = keyof typeof en;
